
import { headers } from 'next/headers';

import clientPromise from '@/lib/mongodb';

//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import '@fontsource/roboto/300.css?v=1.0.8';
import '@fontsource/roboto/400.css?v=1.0.8';
import '@fontsource/roboto/500.css?v=1.0.8';
import '@fontsource/roboto/700.css?v=1.0.8';

import { Providers } from './providers';

import "./globals.scss?v=1.0.8";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	//title: "test",
// 	//description: "Generated by create next app",
// };

export async function generateMetadata() {
	const headersList = await headers();
	const host = headersList.get('host');
	const pathname = `${headersList.get('x-pathname')}`;

	const client = await clientPromise;
	const db = client.db('oryk');

	const provider: any = await db.collection('profiles').findOne({
		category: 'providers',
		hosts: host,
	}, {
		projection: {
			title: 1,
			description: 1,
			_id: 1,
		}
	}) || {};

	const page: any = await db.collection('profiles').findOne({
		category: 'pages',
		hosts: host,
		slug: pathname
	}, {
		projection: {
			title: 1,
			description: 1,
			_id: 1,
		}
	}) || {};

	provider.title = provider?.title || 'Site';

	let title = provider.title;

	if (pathname) title = ` ${`${pathname}`.toUpperCase().split('/').join(' | ')} - ${provider.title}`;

	if (page?.title) title = `${page.title} - ${provider.title}`;

	if (!page?._id) title = `Page Not Found - ${provider.title}`;

	return {
		title,
		description: page?.description || provider?.description,
	};
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en" style={{
			backgroundColor: '#000000',
		}}>
			<head>

				<link rel="icon" href="/favicon.ico" />
				<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
				<link rel="manifest" href="/site.webmanifest" />

				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="theme-color" content="#000000" />

			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>
					{children}
				</Providers>

				<script src="/vendor/jquery-3.7.1.min.js?v=1.0.8" async></script>
				<script src="/vendor/utterscroll-master/jquery-scrollable.js?v=1.0.8" async></script>
				<script src="/vendor/utterscroll-master/debiki-utterscroll.js?v=1.0.8" async></script>
			</body>
		</html>
	);

}
